import { Template } from 'meteor/templating';
import { ReactiveVar } from 'meteor/reactive-var';

import './main.html';

Template.hello.events({
  'click #generate': function () {

      var titles = [
      "All The Lazy Dykes",
      "Alma Matters",
      "Alsatian Cousin",
      "Ambitious Outsiders",
      "America Is Not The World",
      "Ammunition",
      "Angel, Angel, Down We Go Together",
      "Asian Rut",
      "At Amber",
      "Bed Took Fire, The",
      "Bengali In Platforms",
      "Best Friend On The Payroll",
      "Bigmouth Strikes Again",
      "Billy Budd",
      "Black Eyed Susan",
      "Born To Hang",
      "Boxers",
      "Boy Racer, The",
      "Break Up The Family",
      "Certain People I Know",
      "Come Back To Camden",
      "Cosmic Dancer",
      "Dagenham Dave",
      "Dial-A-Cliché",
      "Disappointed",
      "Don't Make Fun Of Daddy's Voice",
      "Do Your Best And Don't Worry",
      "Driving Your Girlfriend Home",
      "East West",
      "Edges Are No Longer Parallel, The",
      "Everyday Is Like Sunday",
      "First Of The Gang To Die",
      "Found Found Found",
      "Friday Mourning",
      "Get Off The Stage",
      "Girl Least Likely To",
      "Glamorous Glue",
      "Hairdresser On Fire",
      "Harsh Truth Of The Camera Eye, The",
      "Have-A-Go Merchant",
      "Headmaster Ritual, The",
      "He Cried",
      "He Knows I'd Love To See Him",
      "Heir Apparent",
      "Hold On To Your Friends",
      "How Can Anybody Possibly Know How I Feel",
      "How Soon Is Now?",
      "I Am Hated For Loving",
      "I Am Two People",
      "I Can Have Both",
      "I'd Love To",
      "I Don't Mind If You Forget Me",
      "I Have Forgiven Jesus",
      "I Know It's Gonna Happen Someday",
      "I Know Very Well How I Got My Name",
      "I Like You",
      "I'm Not Sorry",
      "I'm Playing Easy To Get",
      "(I'm) The End Of The Family Line",
      "Interesting Drug",
      "Interlude",
      "Irish Blood, English Heart",
      "It's Hard To Walk Tall When You're Small",
      "I've Changed My Plea To Guilty",
      "Jack The Ripper",
      "Journalists Who Lie",
      "King Leer",
      "Last Night I Dreamt That Somebody Loved Me",
      "Last Of The Famous International Playboys, The",
      "Late Night, Maudlin Street",
      "Lazy Sunbathers, The",
      "Let Me Kiss You",
      "Let The Right One Slip In",
      "Lifeguard Sleeping, Girl Drowning",
      "Little Man, What Now?",
      "London",
      "Loop, The",
      "Lost",
      "Lucky Lisp",
      "Maladjusted",
      "Margaret On The Guillotine",
      "Mexico",
      "Michael's Bones",
      "Moonriver",
      "More You Ignore Me, The Closer I Get, The",
      "Munich Air Disaster 1958",
      "Mute Witness",
      "My Insatiable One",
      "My Life Is A Succession Of People Saying Goodbye",
      "My Love Life",
      "National Front Disco, The",
      "Never Played Symphonies, The",
      "Nobody Loves Us",
      "Noise Is The Best Revenge",
      "No One Can Hold A Candle To You",
      "November Spawned A Monster",
      "Now I Am A Was",
      "Now My Heart Is Full",
      "Oh Phoney",
      "Oh Well I'll Never Learn",
      "Operation, The",
      "Ordinary Boys, The",
      "Ouija Board, Ouija Board",
      "Our Frank",
      "Papa Jack",
      "Pashernate Love",
      "Piccadilly Palare",
      "Please Help The Cause Against Loneliness",
      "Pregnant For The Last Time",
      "Public Image, The",
      "Reader Meet Author",
      "Redondo Beach",
      "Roy's Keen",
      "Rubber Ring",
      "Rush And A Push And The Land Is Ours, A",
      "Satan Rejected My Soul",
      "Seasick, Yet Still Docked",
      "Shoplifters Of The World Unite",
      "Sing Your Life",
      "Sister I'm A Poet",
      "Skin Storm",
      "Slum Mums, The",
      "Sorrow Will Come In The End",
      "Southpaw",
      "Speedway",
      "Spring-Heeled Jim",
      "Striptease With A Difference",
      "Subway Train",
      "Such A Little Thing Makes Such A Big Difference",
      "Suedehead",
      "Sunny",
      "Swallow On My Neck, A",
      "Sweet And Tender Hooligan",
      "Teachers Are Afraid Of The Pupils, The",
      "Teenage Dad On His Estate",
      "That's Entertainment",
      "There Is A Light That Never Goes Out",
      "There Speaks A True Friend",
      "There's A Place In Hell For Me And My Friends",
      "This Is Not Your Country",
      "Tomorrow",
      "Tony The Pony",
      "Trash",
      "Trouble Loves Me",
      "Used To Be A Sweet Boy",
      "We Hate It When Our Friends Become Successful",
      "We'll Let You Know",
      "Whatever Happens, I Love You",
      "Why Don't You Find Out For Yourself",
      "Wide To Receive",
      "Will Never Marry",
      "World Is Full Of Crashing Bores, The",
      "Yes, I Am Blind",
      "You Know I Couldn't Last",
      "You Must Please Remember",
      "You're Gonna Need Someone On Your Side",
      "You're The One For Me Fatty",
      "You've Had Her",
      "Accept Yourself",
      "Ask",
      "Asleep",
      "Back To The Old House",
      "Barbarism Begins At Home",
      "Bigmouth Strikes Again",
      "Boy With The Thorn In His Side, The",
      "Cemetry Gates",
      "Death At One's Elbow",
      "Death Of A Disco Dancer",
      "Don't Blow Your Own Horn",
      "Draize Train, The",
      "Frankly, Mr. Shankly",
      "Girl Afraid",
      "Girlfriend In A Coma",
      "Golden Lights",
      "Half A Person",
      "Hand In Glove",
      "Hand That Rocks The Cradle",
      "Handsome Devil",
      "Headmaster Ritual, The",
      "Heaven Knows I'm Miserable Now",
      "How Soon Is Now?",
      "I Don't Owe You Anything",
      "I Keep Mine Hidden",
      "I Know It's Over",
      "I Misses You",
      "I Started Something I Couldn't Finish",
      "I Want A Boy For My Birthday",
      "I Want The One I Can't Have",
      "I Won't Share You",
      "Is It Really So Strange?",
      "Jeane",
      "Last Night I Dreamt That Somebody Loved Me",
      "London",
      "(Marie's The Name) His Latest Flame",
      "Matter Of Opinion, A",
      "Meat Is Murder",
      "Miserable Lie",
      "Money Changes Everything",
      "Never Had No One Ever",
      "(Now And Then There's) A Fool Such As I",
      "Nowhere Fast",
      "Oscillate Wildly",
      "Paint A Vulgar Picture",
      "Panic",
      "Please Please Please Let Me Get What I Want",
      "Pretty Girls Make Graves",
      "The Queen Is Dead",
      "Reel Around The Fountain",
      "Rubber Ring",
      "Rush And A Push And The Land Is Ours, A",
      "Rusholme Ruffians",
      "Shakespeare's Sister",
      "Sheila Take A Bow",
      "Shoplifters Of The World Unite",
      "Some Girls Are Bigger Than Others",
      "Still Ill",
      "Stop Me If You Think You've Heard This One Before",
      "Stretch Out And Wait",
      "Suffer Little Children",
      "Sweet And Tender Hooligan",
      "That Joke Isn't Funny Anymore",
      "There Is A Light That Never Goes Out",
      "These Things Take Time",
      "This Charming Man",
      "This Night Has Opened My Eyes",
      "Unhappy Birthday",
      "Unloveable",
      "Vicar In A Tutu",
      "Well I Wonder",
      "What Difference Does It Make?",
      "What Do You See In Him?",
      "What She Said",
      "What's The World",
      "William It Was Really Nothing",
      "Wonderful Woman",
      "Work Is A Four Letter Word",
      "You Just Haven't Earned It Yet Baby",
      "You've Got Everything Now",
      "Fifteen minutes with you",
      "you were virtually dead",
      "you were easily led",
      "and they were half-right",
      "Oh, people see no worth in you",
      "I dreamt about you last night",
      "and I fell out of bed twice",
      "You can pin and mount me like a butterfly",
      "take me to the haven of your bed",
      "was something that you never said",
      "I've seen you smile",
      "but I've never really heard you laugh",
      "There's something against us","" +
      "it's not time, it's not time",
      "so, goodbye, goodbye, goodbye, goodbye",
      "I know I need hardly say how much I love your casual way",
      "The dark nights are drawing in",
      "and your humour is as black as them",
      "I look at yours, you laugh at mine",
      "and 'love' is just a miserable lie",
      "You have destroyed my flower-like life",
      "You have corrupt my innocent mind",
      "Nobody ever looks at me twice",
      "I'm not the man you think I am",
      "Give in to lust, give up to lust",
      "oh heaven knows we'll soon be dust",
      "I could have been wild",
      "and I could have been free",
      "but Nature played this trick on me",
      "She wants it now snd she will not wait",
      "but she's too rough and I'm too delicate",
      "And when darknesss lifts",
      "and the room is bright",
      "I'll still be by your side",
      "for you are all that matters",
      "and I'll love you to till the day I die",
      "I would go out tonight",
      "but I haven't got a stitch to wear",
      "This man said",
      "He knows so much about these things",
      "Does the body rule the mind or",
      "does the mind rule the body?",
      "Under the iron bridge we kissed and",
      "although I ended up with sore lips",
      "it just wasn't like the old days anymore",
      "No, it's not like any other love.",
      "This one is different - because it's us",
      "Hand in glove, we can",
      "go wherever we please and",
      "everything depends upon how near you stand to me",
      "And if the people stare",
      "then the people stare.",
      "I really don't know and I really don't care",
      "We've something they'll never have",
      "If they dare touch a hair on your head",
      "I'll fight to the last breath",
      "But I know my luck too well",
      "Yes, I know my luck too well",
      "and I'll probably never see you again",
      "All men have secrets and",
      "here is mine, so let it be known: ",
      "For we have been through hell",
      "and high tide",
      "I think I can rely on you and",
      "yet you start to recoil heavy words are so lightly thrown",
      "But still I'd leap in front of a flying bullet for you",
      "I stole and I lied, and why? Because you asked me to!",
      "I'm feeling very sick and",
      "and ill today but I'm still fond of you",
      "You should never go to them",
      "let them come to you just like I do",
      "Life is never kind but",
      "I know what will make you smile tonight",
      "Oh, wherever he has gone, I have",
      "We may be dead and we may be gone but",
      "we will be, we will be, we will be",
      "right by your side until the day you die",
      "this is no easy ride",
      "We will haunt you when you laugh",
      "yes, you could say we're a team.",
      "You might sleep, you might sleep, you might sleep",
      "but you will never dream",
      "I don't dream about anyone - except",
      "Oh, the alcoholic afternoons",
      "when we sat in your room",
      "they meant more to me than any",
      "than any living thing on earth.",
      "They had more worth than any living thing on earth",
      "You shut your mouth, how can you say",
      "I go about things the wrong way?",
      "I am a human and I need to be loved",
      "just like everybody else does",
      "There's a club, if you'd like to go",
      "You could meet somebody who",
      "So you go, and you stand on your own",
      "and you leave on your own and you go home, and",
      "you cry and you want to die",
      "When you say it's gonna happen 'now'",
      "well, when exactly do you mean?",
      "See, I've already waited too long and",
      "all my hope is gone",
      "You ask me the time but I",
      "sense something more and",
      "I would like to give what",
      "I think you're asking for",
      ", you handsome devil",
      "There's more to life than books, you know... but",
      "I was looking for a job, and",
      "then I found a job",
      "and heaven knows I'm miserable now",
      "In my life, why do I give valuable time,",
      "to people who don't care if I live or die?",
      "What she asked of me at the end of the day",
      "Caligula would have blushed",
      "In my life, why do I smile at people",
      "who I'd much rather kick in the eye?",
      "Save your life because you've only got one",
      "Anything is hard to find when you",
      "will not open your eyes.",
      "When will you accept yourself?",
      "Girl afraid, where do his intentions lay?",
      "Or does he even have any? She says: ",
      "Prudence never pays and everything she wants",
      "When you cycled by, here began all my",
      "dreams: the saddest thing I've ever seen",
      "And you never knew how much I really liked you because",
      "I never even told you.. Oh, and I meant to",
      "Good times for a change",
      "See, the luck I've had can make a",
      "good man turn bad",
      "So please, please, please, let me",
      "let me get what I want this time.",
      "Haven't had a dream in a long time",
      "See, the life I've had can make a good man",
      "So for once in my life let me get what I ",
      "Lord knows, it would be the first time",
      "I wanna go home, I don't wanna ",
      "Give up education as a bad mistake",
      "She is Famous, she is",
      "funny, an engagement ring doesn't mean a thing to",
      "a mind consumed by brass",
      "I might walk home alone but",
      "but my faith in love is still",
      "So scratch my name on your arm with",
      "On the day that your mentality decides to",
      "try to catch up with your biology, come round",
      "He killed a policeman when he was thirteen and",
      "somehow that really impressed me",
      "and it's written all over my face",
      "And if you ever need self-validation, just meet me in",
      "the alley by the Railway station",
      "It's all over my face",
      "How come someone hasn't noticed that I'm",
      "dead and decided to bury me?",
      "God knows, I'm ready!",
      "I smoke 'cos I'm hoping for an early death",
      "and I need to cling to something.",
      "I just might die with a",
      "a smile on my face, after all",
      "I've seen this happen in other people's lives and",
      "and now it's happening in mine",
      "I think about life and",
      "and I think about death",
      "and neither one particularly appeals to me",
      "Well, I wonder, do you hear me when",
      "Please keep me in mind",
      "A crack on the head is just what you get",
      "This beautiful creature must die",
      "Who hears when animals cries?",
      "Oh has the world changed, or have I changed?",
      "We can go for a walk where it's quiet and dry and talk about",
      "precious things, like love and law and poverty",
      "Oh, these are the things that kill me",
      "Life is very long, when you're lonely",
      "I want to leave, you will not miss me",
      "I want to go down in musical history",
      "I want to live and I want to Love",
      "I want to catch something that I might be ashamed of",
      "She needs you more than she loves you",
      "If you're so funny, then why",
      "are you on your own tonight?",
      "And if you're so clever, then why",
      "are you on your own tonight?",
      "If you're so very entertaining, then why",
      "are you on your own tonight?",
      "If you're so very good-looking, why do you",
      "sleep alone tonight?",
      "Cause tonight is just like any other night",
      "that's why you're on your own tonight.",
      "With your triumphs and your charms",
      "while they're in each other's arms",
      "It's so easy to laugh, it's so easy to hate",
      "It takes guts to be gentle and kind",
      "Love is natural and real but",
      "not for such as you and I, my love",
      "I had a really bad dream, it",
      "it lasted 20 years, 7 months, and 27 days",
      "I never, I'm alone, and",
      "With loves, and hates and passions just like mine",
      "they were born and then they lived and",
      "then they died.",
      "It seems so unfair I want to cry",
      "weird lover Wilde is on mine",
      "Sweetness, sweetness I was only",
      "joking when I said I'd like to",
      "smash every tooth in your head",
      "Now I know how Joan of Arc felt",
      "I've got no right to take my place with",
      "the human race",
      "How can they look into my eyes and",
      "still they don't believe me?",
      "How can they hear me say those words and",
      "still they don't believe me?",
      "And, if they don't believe me now, will they",
      "How can they see the love in our eyes and still",
      "still they don't believe us?",
      "And, after all this time, they don't want to believe us",
      "And, if they don't believe us now, will they ever believe us?",
      "And when you want to live, how do you start?",
      "Where do you go?",
      "Who do you need to know?",
      "He's not strange",
      "he just wants to live his life this way",
      "Take me out tonight",
      "where there's music and there's people and",
      "they're young and alive",
      "Driving in your car, I",
      "never want to go home",
      "because I haven't got one anymore",
      "cause I want to see people and I want to see life",
      "oh, please don't drop me home, cause it's not my home",
      "it's their home, and I'm welcome no more",
      "And, if a double-decker bus crashes into us, to die by your side is such a heavenly way to die. And, if a ten-ton truck kills the both of us, to die by your side.. Well, the pleasure - the privilege is mine",
      "Take me out tonight, take me anywhere, I don't care",
      "I don't care, I don't care. And in the darkened underpass I thought 'Oh God, my chance has come at last', but then a strange fear gripped me and I just couldn't ask.",
      "Oh, There Is A Light And It Never Goes Out",
      "Some girls are bigger than others",
      "Send me the pillow, the one that you dream on, and I'll send you mine",
      "Burn down the disco, hang the blessed DJ, cecause the music that they constantly play, it says nothing to me about my life",
      "Shyness is nice, and shyness can stop you from doing all the things in life you'd like to. So, if there's something you'd like to try, if there's something you'd like to try, ask me, I won't say no... How could I?",
      "Coyness is nice, and coyness can stop you from saying all the things in life you'd like to..",
      "Because if it's not love. then it's the bomb that will bring us together",
      "Nature is a language - can't you read?",
      "You left your tired family grieving and you think they're sad because you're leaving... But did you see jealousy in the eyes of the ones who had to stay behind?",
      "Throw your skinny body down, son!",
      "Throw your white body down!",
      "But I'm going to meet the one I love, so please don't stand in my way",
      "But I'm going to meet the one I love, at last",
      "Learn to love me, assemble the ways.. Now, today, tomorrow and always",
      "I was bored before I even began",
      "Sing me to sleep, I don't want to wake up on my own anymore",
      "I know I'm unloveable, you don't have to tell me. Oh, message received, loud and clear, loud and clear. I don't have much in my life but take it - it's yours",
      "I wear Black on the outside 'cause Black is how I feel on the inside. And if I seem a little strange.. Well, that's because I am. But I know that you would like me if only you could see me, if only you could meet me",
      "Call me morbid, call me pale, I've spent six years on your trail.. Six long years on your trail. Call me morbid, call me pale, I've spent six years on your trail, six full years of my life on your trail",
      "And if you have five seconds to spare then I'll tell you the story of my life: Sixteen, clumsy and shy, I went to London and I, I booked myself in at the Y.W.C.A.",
      "I said: 'I like it here - can I stay? I like it here - can I stay? Do you have a vacancy For a cack-scrubber?'",
      "She was left behind, and sour and she wrote to me, equally dour. She said : 'In the days when you were hopelessly poor, I just liked you more...'",
      "All the lies that you make up, what's at the back of your mind? Oh, your face I can see and it's desperately kind... But what's at the back of your mind?",
      "God, how sex implores you to let yourself lose yourself",
      "You must suffer and cry for a longer time, you just haven't earned it yet, baby",
      "When all I wanted from life was to be famous. I have tried for so long, it's all gone wrong",
      "You must stay on your own for slightly longer.. You just haven't earned it yet baby",
      "A sad fact widely known, the most impassionate song to a lonely soul is so easily outgrown. But don't forget the songs that made you smile and the songs that made you cry when you lay in awe on the bedroom floor and said: 'Oh, oh, smother me Mother'",
      "The passing of time and all of its crimes is making me sad again. The passing of time and all of its sickening crimes is making me sad again. But don't forget the songs that made you cry and the songs that saved your life.. Yes, you're older now and you're a clever swine. But they were the only ones who ever stood by you",
      "The passing of time leaves empty lives, waiting to be filled.. I'm here with the cause, I'm holding the torch in the corner of your room, can you hear me? And when you're dancing and laughing and finally living hear my voice in your head and think of me kindly",
      "Do you love me like you used to?",
      "You're clever, everybody's clever nowadays. You are sleeping, you do not want to believe",
      "Golden lights displaying your name, golden lights it's a terrible shame. But oh my darling, why did you change? Boy in a million, idol, a big star. I didn't tell you how great you were.",
      "Who do you turn to when you're backstage? Don't you remember you once knew a girl you loved her more than the world?",
      "I left the North, I travelled South, I found a tiny house and I can't help the way I feel. Oh yes, you can kick me and you can punch me and you can break my face.. But you won't change the way I feel, 'cause I love you",
      "Oh, is it really so, really so strange? I say no, you say yes (and you will change your mind)",
      "I left the South, I travelled North, I got confused - I killed a horse. I can't help the way I feel. Oh yes, you can punch me and you can butt me and you can break my spine but you won't change the way I feel 'cause I love you",
      "Why is the last mile the hardest mile? My throat was dry, with the sun in my eyes And I realised, I realised I could never, I could never, never, never, go back home again",
      "Is it wrong to want to live on your own? No, it's not wrong - but I must know: how can someone so young",
      "Sing words so sad?",
      "Come out and find the one that you love and who loves you",
      "Is it wrong not to always be glad? No, it's not wrong - but I must add: How can someone so young sing words so sad?",
      "Throw your homework onto the fire, come out and find the one that you love",
      "He was a sweet and tender hooligan, hooligan. And he said that he'd never, never do it again. And of course he won't (oh, not until the next time)",
      "Will you free me? Will you find me?",
      "My eyes have seen the glory of the sacred wunderkind: you took me behind a dis-used railway line and said 'I know a place where we can go where we are not known' and you gave me something that I won't forget too soon",
      "You know where you came from, you know where you're going and you know where you belong. You said I was ill, and you were not wrong but I can't believe you'd ever care and this is why you will never care... These things take time. I know that I'm the most inept that ever stepped",
      "Oh, the alcoholic afternoons, when we sat in your room, they meant more to me than any, than any living thing on earth. They had more worth than any living thing on earth",
      "When you cycled by, here began all my dreams. The saddest thing I've ever seen. And you never knew how much I really liked you because I never even told you.. Oh, and I meant to",
      "There's too much caffeine in your bloodstream and a lack of real spice in your life",
      "Don't mention love",
      "And people who are uglier than you and I, they take what they need, and just leave",
      "Typical me: I started something and now I'm not too sure",
      "Love, peace and harmony? Oh, very nice... But maybe in the next world",
      "There were times when I could have strangled her. But you know, I would hate anything to happen to her.",
      "Let me whisper my last goodbyes",
      "Nothing's changed, I still love you, oh, I still love you. Only slightly, only slightly less than I used to, my love",
      "So I drank one, it became four. And when I fell on the floor I drank more",
      "Last night I dreamt that somebody loved me. No hope, no harm, just another false alarm. Last night I felt real arms around me. No hope, no harm, just another false alarm. So, tell me how long before the last one? And tell me how long before the right one? The story is old - I know - but it goes on",
      "I've come to wish you an unhappy birthday, 'cause you're evil and you lie. And if you should die, I may feel slightly sad but I won't cry..",
      "From the one you left behind.",
      "I touched you at the soundcheck, you had no real way of knowing in my heart I begged 'Take me with you I don't care where you're going'",
      "They cannot hurt you, my darling. They cannot touch you now. But me and my 'true love' will never meet again",
      "Oh, Glenn, don't come to the house tonight because you'll slip on the trail of all my sad remains, that's why, that's why. Goodbye my love.",
      "I want the freedom and I want the guile. Oh, life tends to come and go, as long as you know I won't share you, no. I won't share you. I'll see you somewhere, I'll see you sometime, darling",
    ];

    var terminals = {};
    var startwords = [];
    var wordstats = {};

    for (var i = 0; i < titles.length; i++) {
      var words = titles[i].split(' ');
      terminals[words[words.length-1]] = true;
      startwords.push(words[0]);
      for (var j = 0; j < words.length - 1; j++) {
        if (wordstats.hasOwnProperty(words[j])) {
          wordstats[words[j]].push(words[j+1]);
        } else {
          wordstats[words[j]] = [words[j+1]];
        }
      }
    }

    // Loop to create 10 song titles for a 'new' Morrissey album! :-)
    for (var m = 0; m < 11; m++) {

      var choice = function (a) {
        var i = Math.floor(a.length * Math.random());
        return a[i];
      };

      var make_title = function (min_length) {
        word = choice(startwords);
        var title = [word];
        while (wordstats.hasOwnProperty(word)) {
          var next_words = wordstats[word];
          word = choice(next_words);
          title.push(word);
          if (title.length > min_length && terminals.hasOwnProperty(word)) break;
        }
        if (title.length < min_length) return make_title(min_length);
        return title.join(' ');
      };

      var title = make_title(3 + Math.floor(3 * Math.random()));
      console.log('#generated_title' + m);
      $('#generated_title' + m).html(title);

    } // Close of 12 song loop

  } // Close of click function
}); // Close of template.hello.events